; =============================================================================
; nmi.s — NMI handler (the game's heartbeat)
;
; The NMI fires once per VBlank, ~60 times per second on NTSC. This is the
; closest the NES has to a "game loop" — it's the timer everything runs on.
;
; DESIGN PRINCIPLE — the NMI handler as orchestrator:
; The NMI handler should read like a table of contents, not an instruction manual.
; It calls subroutines and does nothing else. Anyone reading it sees WHAT
; happens each frame at a glance. HOW each thing happens is in the subroutines.
;
; This is assembly's answer to encapsulation: not hiding data, but hiding
; implementation. The NMI doesn't know (or care) how update_player works.
; It just knows it needs to be called first, before anything reads its outputs.
;
; VBLANK BUDGET:
; NTSC VBlank lasts ~2273 CPU cycles. OAM DMA alone consumes 513-514 cycles.
; Keep NMI handlers lean. If you run out of VBlank time, sprites and BG
; will glitch as the PPU starts rendering mid-update.
; =============================================================================

.segment "CODE"

; ---------------------------------------------------------------------------
; nmi_handler
;
; Call order is significant — subroutines communicate through zero-page
; variables, so callers must run before the things that read their outputs:
;
;   1. update_player    reads controller → writes sam_x, sam_y, moving,
;                                          note_index, duty_cycle
;   2. update_sound     reads moving, note_index, duty_cycle → drives APU
;   3. update_oam       reads sam_x, sam_y → writes shadow OAM Y/X bytes
;   4. update_animation reads moving, anim_frame → writes shadow OAM tile bytes
;   5. OAM DMA          syncs shadow OAM ($0200-$02FF) to PPU OAM
; ---------------------------------------------------------------------------
.proc nmi_handler
    jsr update_player       ; controller → movement + note/duty selection
    jsr update_sound        ; movement + note → APU registers
    jsr update_oam          ; position → shadow OAM Y and X bytes
    jsr update_animation    ; movement → shadow OAM tile index bytes

    ; --- OAM DMA: copy shadow OAM to PPU ---
    ; The PPU has its own internal OAM that it reads during rendering.
    ; Our CPU-side shadow ($0200-$02FF) is the staging area. DMA is the
    ; bridge that syncs them. Must happen every frame.
    lda #$00
    sta OAMADDR             ; always reset OAM write position to 0 before DMA
    lda #SHADOW_OAM_PAGE    ; $02 → source is $0200-$02FF
    sta OAMDMA              ; triggers the copy; CPU stalls ~514 cycles

    rti                     ; return from interrupt (restores P and PC from stack)
.endproc


; ---------------------------------------------------------------------------
; irq_handler
;
; IRQs are disabled by SEI in reset_handler, so this never runs in our demo.
; On the NES, IRQs can be generated by the APU frame counter, the DMC
; sample channel, or certain mapper chips. We stub it out with RTI.
; ---------------------------------------------------------------------------
.proc irq_handler
    rti
.endproc
